# Travis CI configuration file
notifications:
  email: false

dist: trusty

sudo: required

addons:
  apt:
    packages:
      - texlive-full
      - biber

script:
  - make -C beamerntnu2015
  - make -C beamerthementnu2017
